[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 921600
upload_speed = 921600
upload_protocol = esptool
board_build.flash_size = 4MB
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.partitions = partitions/huge_app.csv
board_build.filesystem = spiffs
build_flags =
    -I include
    -std=gnu++17
    -D CORE_DEBUG_LEVEL=0
lib_deps =
    https://github.com/pschatzmann/ESP32-A2DP.git#v1.8.10
lib_ldf_mode = chain+
extra_scripts = pre:scripts/platformio_framework_compat.py
