#pragma once

#define DONGLE_TARGET_ESP32_WROOM32 1
#define DONGLE_ENABLE_WIFI 1
#define DONGLE_ENABLE_BLUETOOTH 1
#define DONGLE_ENABLE_BLE 1
#define DONGLE_ENABLE_A2DP 1

#ifndef CORE_DEBUG_LEVEL
#define CORE_DEBUG_LEVEL 0
#endif
